### ISSUE TITLE
Checking UE 5.4 textures exported with fmodel

### ISSUE THREAD

**Issue by KIZILANDO** [matyalatte/UE4-DDS-Tools#35]
I get this error when I check version of 5.4 uasset textures
![image](https://github.com/matyalatte/UE4-DDS-Tools/assets/85397006/a3cead47-ca4a-44be-a3e7-ac5b2b8b3244)

**Comment by KIZILANDO** [comment]
The error is 
`File Summary
  file size: 384
  cooked header size: 790
  name directory offset: 52
  import directory offset: 248
  export directory offset: 272
  unversioned: True
Names
  0: None
  1: PF_DXT1
  2: colt_with_face_tex
  3: /bbc87fb9-41a3-5002-6d05-fa9c8a4672d2/Colt/colt_with_face_tex
Imports
  Texture2D
    type: 1
    id: 0x1b93bca796d1fa6f
    class: Class
    package_name: /Script/Engine
  /Script/Engine
    type: 1
    id: 0x11acced3dc7c0922
    class: Package
    package_name: None
  Default__Texture2D
    type: 1
    id: 0x2bfad34ac8b1f6d0
    class: Texture2D
    package_name: /Script/Engine
Exports
  colt_with_face_tex
    class: Texture2D
    super: None
    template: Default__Texture2D
    size: 2097299
    offset: 0
    is public: True
    is standalone: True
    is base: False
    object flags: 11
Main Export Class: Texture2D
colt_with_face_tex: (offset: 0)
    bulk type: UEXP
    data size: 2097152
    offset: 123
    width: 2048
    height: 2048
Comparing C:\Users\user\Documents\FModel\Output\Exports\FortniteGame\Plugins\GameFeatures\bbc87fb9-41a3-5002-6d05-fa9c8a4672d2\Content\Colt\colt_with_face_tex.uasset and C:\Users\user\AppData\Local\Temp\tmpblb54jxv\colt_with_face_tex.uasset...
Traceback (most recent call last):
  File "C:\Users\user\Downloads\FMT\src\main.py", line 580, in <module>
    main(args, config=config)
  File "C:\Users\user\Downloads\FMT\src\main.py", line 528, in main
    results = [func(folder, file, args)]
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\FMT\src\main.py", line 99, in caller
    raise e
  File "C:\Users\user\Downloads\FMT\src\main.py", line 96, in caller
    response = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/user\Downloads\FMT\src\main.py", line 142, in valid
    compare(f"{old_name}.{ext}", f"{new_name}.{ext}")
  File "C:\Users\user\Downloads\FMT\src\util.py", line 64, in compare
    raise RuntimeError(f"Not same :{i}")
RuntimeError: Not same :2097683`

**Comment by matyalatte** [comment]
Thanks for the testing. Can you share the asset?
> RuntimeError: Not same :2097683

That should be a new issue. It failed to reconstruct binary data somehow.

**Comment by matyalatte** [comment]
Fixed at 8e150f80a873ef1bf317429be3e7500d4ba98c22.

The latest build is available here.
https://github.com/matyalatte/UE4-DDS-Tools/actions/runs/8922932485

I'll close this issue with v0.6.1 release.

**Comment by KIZILANDO** [comment]
Thanks ! So I tested it, works for some textures but still not working for other I'm sending you one that don't work : https://www.mediafire.com/file/em8139gagquibrf/T_Vigilante_Yellow_Body_D.uasset/file

**Comment by matyalatte** [comment]
> still not working for other

Thanks for the report. I fixed it at 192cedb39accbe68ff7b123503ee855455f27843.

The latest build is available here.
https://github.com/matyalatte/UE4-DDS-Tools/actions/runs/8934391242

**Comment by KIZILANDO** [comment]
Thanks works ! Now I have a problem with only one file idk if the version is 5.3 or 5.4. Sorry for all this 😭 
Here is the link : https://www.mediafire.com/file/3vlqe45nqp5ryhz/BluePrintTexture022.uasset/file

**Comment by Zer0cipher** [comment]
am facing this issue here is the assets
![image](https://github.com/matyalatte/UE4-DDS-Tools/assets/137117988/a1cf4e2c-e0bf-4f4c-b449-b0cbb7da5d3d)
https://www.mediafire.com/file/z9kktgu4qnxzgdt/NotSoHolyBuilds.uasset/file
https://www.mediafire.com/file/yi7xg8p8anhy5v5/HolyBuilds.uasset/file

**Comment by Zer0cipher** [comment]
when i try to export textures from the assets 
![image](https://github.com/matyalatte/UE4-DDS-Tools/assets/137117988/29c94497-a2b9-4a59-bd27-99c2f4b826a4)

**Comment by matyalatte** [comment]
@KIZILANDO 
> Now I have a problem with only one file to export and check version idk if the version is 5.3 or 5.4. Sorry for all this 😭

Fixed at 9fbdd29f22f5429616ef9784494c9034b0643a68.
The lasted build is available here.
https://github.com/matyalatte/UE4-DDS-Tools/actions/runs/9033163501

**Comment by matyalatte** [comment]
@Zer0cipher 
Which UE version your game uses? Your assets look quite different from the uasset format I know. I assume it's a customized version or something.

**Comment by Zer0cipher** [comment]
thats fortnite and its ue5.4 and thats a UEFN cooked asset idk if he did something to it before cuz thats not my asset

**Comment by matyalatte** [comment]
> thats a UEFN cooked asset

Thanks for the info. So, UEFN uses a heavily customized format, I think.
I opened a new issue for it (#38.) Idk if I'll work on it or not tho.

**Comment by Zer0cipher** [comment]
ok ty

**Comment by matyalatte** [comment]
I'll close this issue with v0.6.1 release. please open a new issue if you get another error.
